# Generated by Django 5.2.17 on 2026-09-30 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_rename_first_name_profile_name'),
        ('blog', '0009_view'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='View',
            new_name='PostView',
        ),
        migrations.AlterField(
            model_name='postview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='accounts.profile'),
        ),
    ]
